### ISSUE TITLE
Explicitly stopping actors weirdness

### ISSUE THREAD

**Issue by robgil** [jodal/pykka#51]
Hey,

Love pykka. I'm just dabbling with concurrent programming so please bear with me.

I understand that there is no supervisor, however I am trying to explicitly stop actors and am not able to get them to stop with a keyboard inturrupt.

``` python
class send_flow(pykka.ThreadingActor):
    # ....

def main():
    logging.basicConfig(level=logging.INFO, format=LOG_FORMAT)
    try:
        for i in range(0,4):
            locals()['actor_{0}'.format(i)] = send_flow.start()
    except KeyboardInterrupt:
        LOGGER.info("Stopping actors...")
        # Close all actors to stop blocking
        for i in pykka.ActorRegistry.get_all():
            LOGGER.info("Stopping Actor: " + i.actor_urn + " ...")
            i.stop()
            LOGGER.info("Stopped Actor: " + i.actor_urn)
        LOGGER.info("Stopped actors.")

if __name__ == '__main__':
    main()
```
I have also tried the pykka.ActorRegistry.stop_all() and that didn't work either. 

Any help would be much appreciated.

**Comment by jodal** [comment]
Sorry for the late answer. I didn't immediately see the problem, so I deferred looking closer at this.

The problem here is that your main thread doesn't do anything after it started the four actors, so it simply went of the cliff and shut down. Then you had noone to react to the `KeyboardInterrupt`.

The following example works nicely:

``` python
import logging
import signal
import time

import pykka
import pykka.debug


LOGGER = logging.getLogger(__name__)


class send_flow(pykka.ThreadingActor):
    pass


def main():
    logging.basicConfig(level=logging.DEBUG)
    signal.signal(signal.SIGUSR1, pykka.debug.log_thread_tracebacks)

    try:
        for i in range(0, 4):
            locals()['actor_{0}'.format(i)] = send_flow.start()
        while True:
            time.sleep(0.1)
    except KeyboardInterrupt:
        LOGGER.info("Stopping actors...")
        # Close all actors to stop blocking
        for i in pykka.ActorRegistry.get_all():
            LOGGER.info("Stopping Actor: " + i.actor_urn + " ...")
            i.stop()
            LOGGER.info("Stopped Actor: " + i.actor_urn)
        LOGGER.info("Stopped actors.")

if __name__ == '__main__':
    main()
```

Now, the Pykka thread state debugger I added also works. The signal handling it uses depends on the main thread being alive and not blocked, ref https://www.pykka.org/en/latest/api/#pykka.debug.log_thread_tracebacks.

**Comment by robgil** [comment]
Oh wow. Thanks so much. Now that you describe it its so obvious.
