### ISSUE TITLE
Continue actor after exception

### ISSUE THREAD

**Issue by huynh91** [jodal/pykka#83]
Hi, 
Is it possible to continue running an actor after an exception occurs? If I remember correctly, 
in Pykka 1.x, we could handle the exception by on_failure() and continue.

**Comment by jodal** [comment]
If someone sends a message to an actor with "ask" semantics, any exceptions raised in the actor are returned to the sender, and the actor continues processing the next incoming message.

If there is nowhere to return the exception, so that someone can handle it, the exception is logged, `on_failure()` is called, and the actor shuts down.

There is no change in this area from Pykka 1.x to 2.x.
